name: Python package

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/my-python@v1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: print version
        run: python app/db.py
      
